# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Désactive la sécurité pour le profiler et les assets
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Désactive complètement la sécurité pour la registration
        registration:
            pattern: ^/register$
            security: false

        # Pare-feu principal pour le reste de l’application
        main:
            pattern: ^/
            provider: app_user_provider
            lazy: true

            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: offre_index
                username_parameter: _username
                password_parameter: _password

            logout:
                path: app_logout
                target: app_login

    access_control:
        # On garde cette règle pour le principe, mais elle est redondante
        - { path: ^/register,      roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/offre/\d+/postuler$, roles: ROLE_USER }
        - { path: ^/offre,         roles: ROLE_USER }
        - { path: ^/candidatures,  roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            App\Entity\User:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
