# config/packages/security.yaml
security:
    # Encodage des mots de passe
    password_hashers:
        App\Entity\User:
            algorithm: auto

    # Chargement des utilisateurs depuis la base via l’entité User
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Désactive la sécurité pour le profiler et les assets
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Pare-feu principal
        main:
            pattern: ^/
            provider: app_user_provider
            lazy: true
            # Formulaire de login
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: offre_index
                username_parameter: _username
                password_parameter: _password
            # Logout
            logout:
                path: app_logout
                target: app_login

    # Contrôles d’accès
    access_control:
        # Seules les personnes authentifiées peuvent accéder aux offres et postuler
        - { path: ^/offre/\d+/postuler$, roles: ROLE_USER }
        - { path: ^/offre,           roles: ROLE_USER }
        # Sécurise l’interface de candidatures
        - { path: ^/candidatures,    roles: ROLE_USER }

# Configurations spécifiques à l’environnement de test
when@test:
    security:
        password_hashers:
            App\Entity\User:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
